spring:
  application:
    name: mstc-service

  data:
    mongodb:
      uri: mongodb+srv://minh160302:Canhminh-160302@cluster0.zimve.mongodb.net/mstc?retryWrites=true&w=majority
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
      database: mstc
#      uri: mongodb://localhost:27017/mstc

  mail:
    host: smtp.gmail.com
    port: 587
    username: minh160302@gmail.com
    password: Nguyencanhminh-160302
    protocol: smtp
    test-connection: false
    default-encoding: UTF-8
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true


  thymeleaf:
    cache: false
    prefix: classpath:/mails/
    suffix: .html
    encoding: UTF-8

  servlet:
    multipart:
      max-file-size: 6MB
      max-request-size: 6MB


server:
  port: 8000


##config aws s3
#aws:
#  s3:
#    access-key: AKIAXORINMPXCK56BCVH
#    secret-key: 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
#    bucket-name: mstc-bucket